# Generated by Django 5.2.12 on 2026-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="is_daily_grind",
            field=models.BooleanField(
                default=True, help_text="Is this a part of your daily grind/routine?"
            ),
        ),
    ]
