# Generated by Django 5.2.12 on 2026-03-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_goal_is_daily_grind"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="is_one_time",
            field=models.BooleanField(
                default=False, help_text="Is this a one-off task for today only?"
            ),
        ),
    ]
