# Generated by Django 5.2.12 on 2026-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reminder_time",
            field=models.TimeField(
                default="20:00",
                help_text="What time should we remind you to update your data?",
            ),
        ),
    ]
