# Generated by Django 5.2.12 on 2026-03-28 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecture_name", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance_proofs/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_late", models.BooleanField(default=False)),
                ("credibility_score", models.FloatField(default=10.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("user", "lecture_name", "date")},
            },
        ),
    ]
