# Generated by Django 5.2.12 on 2026-03-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="scheduled_time",
            field=models.TimeField(
                blank=True,
                help_text="What time was the lecture supposed to start?",
                null=True,
            ),
        ),
    ]
