# Generated by Django 5.2.12 on 2026-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancerecord_scheduled_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="is_attended",
            field=models.BooleanField(
                default=True, help_text="Did you actually attend this session?"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="reason_for_absence",
            field=models.TextField(
                blank=True, help_text="If No, explain why.", null=True
            ),
        ),
    ]
