# Generated by Django 5.2.12 on 2026-03-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendancerecord_is_attended_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="is_late",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="scheduled_time",
        ),
    ]
